### PR TITLE
Introduce CHANGELOG.md

### PR DESCRIPTION
**Pull request by krajek**
Template is taken from [keepthechangelog homepage](http://keepachangelog.com)

### CODE REVIEW

**Comment by krajek** [comment]
@RehanSaeed as usually: let me know if you are OK with introducing changelog. LGTM before next release.
In the future, I will fill the changelog retrospectively for previous releases

**Comment by RehanSaeed** [comment]
I've been using tags to release this project to NuGet, so when you tag the code with a version number e.g. `4.0.0`, AppVeyor builds and does a NuGet push. I also try to keep the release notes section of the nupkeg up to date.

If you go to the `releases` page, you can see the tags (I've been a bit inconsistent with the names and should probably fix that). I've seen some projects which have a changelog on this releases page, we should probably use this feature [built into GitHub](https://github.com/blog/1547-release-your-software). We can even use the NuGet package release notes to fill in the GitHub release notes retrospectively.

**Comment by RehanSaeed** [comment]
I just edited the latest release and GitHub has automatically added the commit details into the release notes for the tag. I think if we use the format in your changelog, we could do better than using git commits.

**Comment by RehanSaeed** [comment]
Also, the benchmark project just got published to NuGet based on the fact that I edited the tags. We need to set `IsPackable` to `false` in the csproj for that project to avoid this happening again. I'll unpublish it for now.

**Comment by krajek** [comment]
@RehanSaeed thanks for the comments. I set `IsPackable` to `false`.
From now on, let's maintain CHANGELOG as the single source of truth. Every other place (github releases, nuget packages) should be based on the CHANGELOG.

**Pull request merged**
