### PR TITLE
[WIP] List based exception properties bag

### PR DESCRIPTION
**Pull request by krajek**
This PR explores the observation that while Dictionary is optimized for random access, the only use case for the collection gathering exception properties is to
a) add items one by one
b) iterate over them once 
List or array may be much better for that.
First results show that both execution time and memory are improving in the benchmark scenario.
```
                         Method |  Job | Runtime |       Mean |      Error |     StdDev |  Gen 0 | Allocated |
------------------------------- |----- |-------- |-----------:|-----------:|-----------:|-------:|----------:|
         ReflectionDestructurer |  Clr |     Clr |   7.302 us |  0.0566 us |  0.0473 us | 2.4796 |   3.81 KB |
 ReflectionDestructurerListDict |  Clr |     Clr |   7.112 us |  0.0528 us |  0.0412 us | 2.0905 |   3.22 KB |
             CustomDestructurer |  Clr |     Clr |   6.128 us |  0.0329 us |  0.0291 us | 2.2354 |   3.44 KB |
     CustomDestructurerListDict |  Clr |     Clr |   5.552 us |  0.1089 us |  0.1118 us | 1.7624 |   2.71 KB |
```
@RehanSaeed or others: any thoughts?

### CODE REVIEW

**Comment by RehanSaeed** [comment]
LGTM

**Comment by krajek** [comment]
I have a holdup on this one. If we use anything else than Dictionary then `Serilog` capturing process will interpret is as IEnumerable<KeyValuePair<string, object>> which will result in ugly JSON.
The key to that is https://github.com/serilog/serilog/blob/e42245c0db0931e1fffdd72a0729361c60e877bc/src/Serilog/Capturing/PropertyValueConverter.cs#L311
```
bool TryGetDictionary(object value, Type valueType, out IDictionary dictionary)
        {
            if (valueType.IsConstructedGenericType &&
                valueType.GetGenericTypeDefinition() == typeof(Dictionary<,>) &&
                IsValidDictionaryKeyType(valueType.GenericTypeArguments[0]))
            {
                dictionary = (IDictionary)value;
                return true;
            }

            dictionary = null;
            return false;
        }
```
This method is hard-wired to a to `Dictionary` type. It seems like I would need to make this method more generic before trying to improve our dictionary implementation :-(

**Comment by krajek** [comment]
Regarding that PR, I will have to close it. `Serilog` requires concrete `Dictionary` class to be present, there is no way to remove that constraint and support older version at the same time.

Regarding the `master` branch: @RehanSaeed what happened, it looks like forced changed master to `3.0.0`? Was it on purpose?

BTW: 4.1 was still not published on nuget, would you publish it after the master goes back to usual?

**Comment by RehanSaeed** [comment]
Thats a shame.

I realized that I was using the wrong email in my git config which meant that the commits were coming in as anonymous. I used [this](https://help.github.com/articles/changing-author-info/) GitHub article to correct it but that was not a good idea as I think it changed the SHA's of the commits. I ran it on some other small repos and it seemed to work ok. I won't ever be doing that again...

What I don't understand is why it says 3.0.0. Can you confirm that the code is all good? I can bump the version and release.

**Comment by krajek** [comment]
`master` branch is was set to the commit `bb306db4e926f6bd8dffb572b6c308ec9b7aa504` which is from Nov 2017. It is also a place where tag `Serilog.Exceptions.3.0.0` points to. 

I have just committed back all the commits that you "removed". `4.1.0` still needs to be published on nuget.

**Pull request closed without merging**
