### PR TITLE
Add XUnit CLI tool reference

### LINKED ISSUE #75: Failing build
@RehanSaeed did you notice that build for `master` branch is failing?
From the history of builds, it seems that the problem showed up after version `4.1`, possibly by merging `dependabot` commits.

Do you have a plan to fix the build?

EDIT: I have just pushed 9fbb55a, which fixes the failing test, part of the problem of failing the build.

### PR DESCRIPTION
**Pull request by krajek**
Closes #75

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Actually, we should remove that reference and change the Cake build script to use `dotnet test`. Will do that in a bit. `dotnet xunit` has been killed and will be removed in the next version of xUnit.

**Comment by krajek** [comment]
I was not aware that `dotnet xunit` is going to be removed. Thanks.

I even started to implement `dotnet test` and it worked, if I skipped xml and html generation,

In case we need xml and/or html we may use https://cakebuild.net/api/Cake.Incubator/DotNetCoreTestExtensions/D1A1B351. Note, that this is an add-on and will not work out of the box.

**Comment by RehanSaeed** [comment]
Made the change to use `dotnet test`. Also simplified and optimised the cake script a little. AppVeyor recognises `.trx` files so I added that to the `.appveyor.yaml` file. Also upgraded the .NET SDK that appveyor and travis install.

**Comment by krajek** [comment]
Looks great, thanks!

**Pull request merged**
