### PR TITLE
Improve the performance reflection part of reflection destructurer

### PR DESCRIPTION
**Pull request by krajek**
`BenchmarkDotNet` library and `Serilog.Exception.Benchmarks` project was added.
The properties of exception types are cached to avoid unnecesary rework.
This gave some small performance improvement.
Initial idea was to add `fastmember` library, but we decided to not add dependency to library that does not seem to be active.

### CODE REVIEW

**Comment by krajek** [comment]
I am starting this PR to let you early review the idea of improving the performance of the reflection destructurer. Unfortunately, usage of `TypeAccessor` from the `fastmember` library did not help even a bit. I will investigate why or work on other solution.

**Comment by krajek** [comment]
|                    Method |     Mean |     Error |    StdDev |
--------------------------- |---------:|----------:|----------:|
  |OldReflectionDestructurer | 30.37 us | 0.5989 us | 0.7575 us |
   |      CustomDestructurer | 18.08 us | 0.3555 us | 0.5429 us |
| FastReflectionDestructurer | 24.94 us | 0.4951 us | 0.6941 us |

First positive results, only change is using `fastmember` instead of "manual" reflection code.

**Comment by RehanSaeed** [comment]
This is cool, a bit sad about having to add a dependency though. Might also be worth adding .NET allocations to the Benchmark, see example [here](https://github.com/ASP-NET-Core-Boilerplate/Framework/blob/master/Benchmarks/Boilerplate.Mapping.Benchmark/MapArrayBenchmark.cs).

Can you use the newer csproj format, add the StyleCop package and use separate files for each class.

Also BTW, there are two issues marked as help wanted if you would like to contribute further. I'll hold off on a release for a bit.

**Comment by RehanSaeed** [comment]
Performance > one more dependency

Good stuff. I'm glad this project was useful enough that it's starting to get contributions.

**Comment by krajek** [comment]
I have an issue, maybe you could take help? When I created benchmark project as .NET Core Console App I got weird benchmark results. All destructurers have times around 800µs. In .NET Framework App as you saw they had times around 20-30µs. Any ideas? If you are interested `fast_reflection_destructurer_netcore_benchmark` is the name of the branch on my fork.

**Comment by RehanSaeed** [comment]
Thats certainly strange. I can't promise to take a look any time soon but I've had success [here](https://github.com/ASP-NET-Core-Boilerplate/Framework/blob/master/Benchmarks/Boilerplate.Mapping.Benchmark/MapArrayBenchmark.cs) with Benchmark.NET where I run benchmarks against both .NET Core and full .NET Framework.

**Comment by krajek** [comment]
FYI results from converting project to multi-target(Core and net46)

|                     Method |  Job | Runtime |       Mean |      Error |     StdDev |
|--------------------------- |----- |-------- |-----------:|-----------:|-----------:|
|  OldReflectionDestructurer |  Clr |     Clr |  15.298 us |  0.1815 us |  0.1516 us |
|         CustomDestructurer |  Clr |     Clr |   6.867 us |  0.0859 us |  0.0804 us |
| FastReflectionDestructurer |  Clr |     Clr |  11.652 us |  0.2179 us |  0.2140 us |
|  OldReflectionDestructurer | Core |    Core | 775.141 us | 10.8932 us | 10.1895 us |
|         CustomDestructurer | Core |    Core | 748.416 us |  4.2248 us |  3.9518 us |
| FastReflectionDestructurer | Core |    Core | 767.221 us | 10.5975 us |  9.9130 us |

The problem with 700+us offset applies equally to every benchmark, thus to all kind of destructurers (even empty benchmarks is 100us). I will postpone fighting with this and plan it for next PR.

**Comment by krajek** [comment]
From my point of view, PR is ready to merge.
I have implemented all the cleanups and improvements you mentioned.
There is just this issue with weird results of benchmark for `CoreJob`, but it seems orthogonal to the changed in this PR, so I will tackle in later.

**Comment by RehanSaeed** [comment]
I've got allocations setup in my [benchmark](https://github.com/ASP-NET-Core-Boilerplate/Framework/blob/master/Benchmarks/Boilerplate.Mapping.Benchmark/BenchmarkDotNet.Artifacts/results/MapArrayBenchmark-report-github.md) (take a look), I'm using:

```
    [ClrJob]
    [CoreJob]
    [MinColumn]
    [MaxColumn]
    [HtmlExporter]
    [CsvMeasurementsExporter]
    [RPlotExporter]
    [MemoryDiagnoser]
```

`RPlotExporter`requires you to install R in Visual Studio. It generates some nice charts too.

**Comment by krajek** [comment]
I don't understand your intent here. I added memory diagnoser, allocations are displayed. Do you need anything else?

In my opinion, all the other attributes(Min, Max, exporters, plots), do not add any value in our case. I would even say that they would be harmful because of decreased signal/volume ration.

**Comment by RehanSaeed** [comment]
Sorry, missed `MemoryDiagnoser` being in there. Will merge after your fix to the tests goes in.

**Comment by shatl** [comment]
Are we talking about this library https://github.com/mgravell/fast-member ? 
Unless application produces hundreds of thousands exceptions I do not believe there would be significant performance improvement. On other side this introduces dependency on the library which does not seem to be under active development / maintenance (see current open issues: https://github.com/mgravell/fast-member/issues ) and nuget was not updated since Aug 2016.

I'd recommend to create an extension point and release this as a separate package.

**Comment by krajek** [comment]
I absolutely confirm and agree that adding a dependency is a cost. I just think, just like @RehanSaeed that in that tradeoff(performance vs one adding one small stable dependency) performance is more important to the project.

Regarding idea to create a separate package, I would also not agree, in context of this library. When I am using Serilog.Exceptions in my projects I rely solely on the reflection destructuring for any non-standard exception. I consider this scenario the most important one for `Serilog.Exceptions`. Just plug it in and go. Therefore, it is a top priority to improve the stability and performance of reflection destructurer(ideally to a point of negligible difference between reflection and custom destructurers).

That said, it is only the context of the work we are doing, that makes this tradeoff worthwhile. On a commercial project, I would oppose such change with exactly the same arguments.

**Comment by krajek** [comment]
@RehanSaeed anything else left to do before the merge?
@shatl apart from the dependency is there anything you would suggest before the merge?

**Comment by RehanSaeed** [comment]
@shatl's comments concern me, we don't want to add a dependency to a slowly dieing library. Also, there is a lot of activity in the .NET Core BCL to improve performance, so one option is to sit tight and wait.

I also found that there may be bugs in this library https://github.com/mgravell/fast-member/issues/46 https://github.com/mgravell/fast-member/issues?q=is%3Aopen+is%3Aissue+label%3AType-Defect, none of which have been acted upon.

**Comment by krajek** [comment]
Ok, thanks for the input. I will disagree but commit to your ideas. I will remove the dependency and just remember properties info table for each type. Then, after the PR, I will look for other ways of improving performance.

**Comment by RehanSaeed** [comment]
Your PR is still valuable. The benchmarks are still good.

**Comment by krajek** [comment]
Yes, of course will just modify this PR instead of starting from scratch :-)

**Comment by krajek** [comment]
Thanks for the comments. `fastmember` dependency was removed.

**Comment by RehanSaeed** [comment]
Cool

**Pull request merged**
