### PR TITLE
Ignore selected properties of an exception

### PR DESCRIPTION
**Pull request by krajek**
Continuation of PR  #32.
User can provide list of ignored properties, which will not be printed
even if present if the exception.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Hi, thanks for your hard work. Did you see https://github.com/RehanSaeed/Serilog.Exceptions/issues/29, I'd like to get your comments.

**Comment by RehanSaeed** [comment]
Lets add one optimization. If there are no ignored properties, add the property as normal. Then I'll merge the PR.

**Comment by krajek** [comment]
Could you please elaborate? 
By "add the property as normal" do you mean avoid calling `lIST.Contains` at all with some `if(ignoreProperties!=null)`?

**Comment by RehanSaeed** [comment]
Exactly. You've got what I mean.

**Comment by krajek** [comment]
I have concluded, that the design is not appropriate. Most importantly, it violates Open Closed Principle. It is not open for extension. 

Therefore, I am closing this PR. I will try another approach, probably with some more generic idea like filter objects(implementing some `IExceptionPropertyFilter` interface). I will come back with another PR.

**Pull request closed without merging**
