### PR TITLE
Add RegexMatchTimeoutExceptionDestructurer for RegexMatchTimeoutException

### PR DESCRIPTION
**Pull request by Driedas**
As per #418, adding a custom destructurer for RegexMatchTimeoutException.
Behold the glory that is my contribution!
/sarcasm ;-)

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Looks good. You've got conflicts for some reason though.

**Comment by Driedas** [comment]
Yeah, I saw that, but am not really sure why, the only change I made in the conflicting file is adding the destructurer into the default set:
image

**Comment by Driedas** [comment]
Ok, got it (thanks to a "friend on the phone"), looks like my git client opened the master branch by default whereas you stopped using master in November 2020 and are using "main" instead. My commit thus ended up in the master branch. Have resolved the conflict via the github merge tool but there is now an ugly merge commit in the log. Can you squash these two while merging the PR or do we start from scratch and I'll submit the PR from the main branch instead?

**Comment by RehanSaeed** [comment]
I ran the pipeline again (GitHub recently required that for new contributors) and there still seems to be a conflict.

**Comment by Driedas** [comment]
ok, I'll drop the whole thing and do it from scratch on the main branch instead of master...

**Pull request closed without merging**
