### PR TITLE
Add support for OperationCancelledException and TaskCancelledException, closes #64

### LINKED ISSUE #64: Do not destructure CancellationToken
Currently exception details is showing CancellationToken like this:
```
    "CancellationToken": {
        "_typeTag": "CancellationToken",
        "IsCancellationRequested": true,
        "CanBeCanceled": true,
        "WaitHandle": "The property accessor threw an exception: ObjectDisposedException"
      },
```
rendering ObjectDisposedException if it is disposed

Should render it as
```
"CancellationToken": "CancellationRequested: true"
```

### PR DESCRIPTION
**Pull request by shatl**
Custom destructurers for CancellationToken and Task

### CODE REVIEW

**Comment by krajek** [comment]
Thanks for the effort @shatl. 

Apart from fixing the build, I would like to see full coverage of tests for `TaskCanceledExceptionDestructurer` and changes in reflection based-destructurer.

You could also make an appropriate entry in `CHANGELOG.md`.

**Comment by shatl** [comment]
Trying to figure out StyleCop settings...

**Comment by krajek** [comment]
@shatl do you plan to finish the PR in some near future? If not, I could chip in and complete it.

**Comment by shatl** [comment]
@krajek not sure, I'm busy with something else. Please chip in

**Comment by krajek** [comment]
Thanks, @shatl for the idea and most of the implementation. I will carry on the work in the next PR.

**Comment by RehanSaeed** [comment]
Thank you both for your effors.

**Pull request closed without merging**
