### PR TITLE
Document public API

### LINKED ISSUE #52: Document every public object in the library
Before 4.0 I want to make sure that every public facing element of API is well documented.

### PR DESCRIPTION
**Pull request by krajek**
Closes #52

### CODE REVIEW

**Comment by krajek** [comment]
Maybe in the future, I will comment literally every public API element and enable strict style cop rule but not yet. I commented most of the APIs, especially those that users will use most often.
@RehanSaeed could take a last look before the merge?

**Comment by RehanSaeed** [comment]
Consider removing the lines related to comments [here](https://github.com/RehanSaeed/Serilog.Exceptions/blob/87ec6382060fb8374e1f93d3969e1dd772133958/MinimumRecommendedRulesWithStyleCop.ruleset#L71). You may get some StyleCop warnings about comments that would need to be fixed.

**Comment by krajek** [comment]
It was painful, but I enabled StyleCop's rule `1600` and filled all the missing documentation.
@RehanSaeed, if you will, please review once again.

**Comment by RehanSaeed** [comment]
Looks cool, I think we can also enable these three StyleCop rules: 

- http://stylecop.soyuz5.com/SA1601.html
- http://stylecop.soyuz5.com/SA1602.html
- http://stylecop.soyuz5.com/SA1623.html

I don't think they will cause many warnings to fix or any in fact. Then lets merge!

**Pull request merged**
